### ISSUE TITLE
Consistency on postback payload behavior: `text.greetings`, `text.help`, and case sensitivity

### ISSUE THREAD

**Issue by stripethree** [CondeNast/launch-vehicle-fbm#38]
Currently postbacks are not compared to `DEFAULT_GREETINGS_REGEX` to see if the payload matches a greeting. The `DEFAULT_GREETINGS_REGEX` covers _get started_ and thus, with the current implementation, the SDK could diverge on behaviors for the postback that comes from a user tapping the _Get Started_ button versus typing _get started_. The payload for the _Get Started_ button can be changed by the application developer, but this does not alleviate the possibilty of different behavior on a postback versus text message.

Additionally, the same issue exists for `text.help`, which is a common item in persistent menus. Clicking on persistent menus trigger postbacks and this a menu item with `help` as the payload will be emitted as `text` instead of `text.help`.

Lastly, postback payloads are also not converted to lower case, which is inconsistent with how text messages are treated when their content is emitted with events.

These can be broken out into separate issues if need be but I thought it useful to start with a larger scoped issue that covers the inconsistencies observed when debugging a bot using the SDK.

CC for comment: @crccheck @nosamanuel @tswicegood

**Comment by nosamanuel** [comment]
Can this be solved at the regex level by using the case-insensitive flag (`/i`)?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

**Comment by stripethree** [comment]
The default regex for both _greetings_ and _help_ have the case-insensitive flag:
```
const DEFAULT_GREETINGS_REGEX = /^(get started|good(morning|afternoon)|hello|hey|hi|hola|what's up)/i;
const DEFAULT_HELP_REGEX = /^help\b/i;
```

The part about case-sensitivity in the summary refers to this:
```
this.emit('text', {event, senderId, session, source: 'text', text: text.toLowerCase().trim()});
```

The `.toLowerCase().trim()` modification establishes the expectation that string comparisons in the application for the `text` event can make certain assumptions:
```
messenger.on('text', ({senderId, text, source}) => {
  if (text === 'something') { // don't need any toLowerCase or trim here!
    return messenger.send(senderId, new Text('a reply'));
  }
  if (text === 'something else') { // or here!
    return messenger.send(senderId, new Text('another reply'));
  }
});
```

However, with `postbacks`, this expectation falls over:
```
onPostback(event, session) {
  this.emit('text', {event, senderId, session, source: 'postback', text: payload});
}
```

Essentially what I'm proposing is to bring that in line, simply:
```
onPostback(event, session) {
  this.emit('text', {event, senderId, session, source: 'postback', text: payload.text.toLowerCase().trim()});
}
```

The `payload` is set by the application developer, so this could be over-engineering, but it creates consistency.

**Comment by crccheck** [comment]
this is something I've been thinking about. I think there should be a distinction between the simplified `text` and the original `text` Right now, I'm essentially doing `text.toLowerCase().toLowerCase()` because I'm not sure what comes in. This reminds me of the api talk where he said if you have to constantly look at the docs, something is wrong.

So perhaps there should be a `text` and `inputText` or `parsedText` or `cleanText`

**Comment by crccheck** [comment]
I was looking at https://data.world/data-society/the-simpsons-by-the-data and they used "name" and "normalized_name", which sounds good to me. So there could be `text` and `normalizedText`

**Comment by stripethree** [comment]
Going to take a crack at this with the input from the comments.

**Comment by crccheck** [comment]
> would cause backward compatibility issues

This is where semver is iffy. I agree it's a backwards incompatible change. But in practice, we were applying `.toLowerCase` twice to everything anyways because it was ambiguous what `text` meant. At this stage, I'd rather not worry too much about preserving backwards compatibility. I added backwards compatibility to #49 at the cost of some tech debt, but mostly because the change was additive.

For naming things, that's just always painful. I'm not even sold on `text` `normalizedText` `originalText`. I think we should get more opinions. The one opinion I have is that since `text` is the shortest, that should be the variable that's the most "useful".

**Comment by stripethree** [comment]
Ok, I think I have a decent solution in the works. I'll get a PR going and we can see what we prefer.
