### ISSUE TITLE
Missing server url in default config

### ISSUE THREAD

**Issue by gautamarora** [CondeNast/launch-vehicle-fbm#63]
Following the [blog post](https://engineering.condenast.io/story/bot-building-with-launch-vehicle-fbm), I copied over the config from the module over to my application but got the error that serverUrl is missing in the default config when starting the application.

```
$ node index.js 
/Users/gautam/develop/node/bot/fbm-test/node_modules/config/lib/config.js:181
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "serverUrl" is not defined
    at Object.Config.get (/Users/gautam/develop/node/bot/fbm-test/node_modules/config/lib/config.js:181:11)
    at Server.app.listen (/Users/gautam/develop/node/bot/fbm-test/node_modules/launch-vehicle-fbm/src/app.js:162:100)
    at Server.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1285:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
Seperately, I was confused on when to use `default.json` and when to use `custom-environment-variables.json`, as I expected custom to override default but since it wasn't working that way I copied all values form custom to default and things worked fine from there on.

**Comment by stripethree** [comment]
> serverUrl is missing in the default config when starting the application

The fix here is to export the URL your bot into the environment with the key `SERVER_URL`: `export SERVER_URL=https://bot.localtunnel.me`. The only default that makes sense would be `https://localhost:3000`, but since Facebook requires a publicly accessible URL, that could cause confusion.

Re: usage of `default.json` and `custom-environment-variables.json`:
* `custom-environment-variables.json` need only be modified if you want to change the the name of an environment variable; an example would be changing `NODE_PORT` to `PORT` in the case of deploying to Heroku, as described [here]. If you want to add a new variable and use the built in capabilities of `node-config`, then that new value gets added to this file as well
* `default.json` need only be modified if you need a fallback value for anything in `custom-environment-variables.json`

[here]: https://github.com/stripethree/enterprise-fbm/pull/8/files#diff-04c6e90faac2675aa89e2176d2eec7d8R50

**Comment by stripethree** [comment]
Looking at this again, what throws the error is a debug message. I am going to split that message up, check for the prescence of `serverUrl` with `config.has` and throw an error message if it is not present. This allows a developer to continue working on their project. Since `serverUrl` is only used in the SDK for _Login with Facebook_ support, I think this is an acceptable work around.
